spring:
  data:
    mongodb:
      database: bank
      host: ${BANK_APP_MONGODB_SERVICE_HOST}
      port: ${BANK_APP_MONGODB_SERVICE_PORT_MONGODB:27017}
      user: bank
      password: bank123
      uri: mongodb://bank:bank123@${BANK_APP_MONGODB_SERVICE_HOST}:${BANK_APP_MONGODB_SERVICE_PORT_MONGODB}/bank
server:
  port: 8081