api:
  host: ${BANK_APP_BANK_CHART_SERVICE_HOST:localhost}
  port: 8085
  #${BANK_APP_BANK_CHART_SERVICE_PORT_HTTP:8085}
  user: asd
  password: basd
server:
  port: 8001

keycloak:
    #serverUrl: http://localhost:8080/auth
    #realm: bank
    #clientId: bank
    #clientSecret: 579f8cf6-2a95-4453-9482-a6914fcd109c
    #publicClient: true
    #resource: product-app
  #serverurl: http://localhost:8080/auth
  realm: bank
  auth-server-url: http://localhost:8080/auth
  resource: product-app
  public-client: true
  enabled: true
  security-constraints[0].authRoles[0]: bank-role
  security-constraints[0].securityCollections[0].patterns[0]: /deposit

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
     host: ${BANK_APP_RABBITMQ_SERVICE_HOST:localhost}
     username: user
     port: ${BANK_APP_RABBITMQ_PORT_5672_TCP_PORT:5672}
     password: XAZvBI2Mfb
     #FIXME