api:
  host: ${BANK_APP_BANK_CHART_SERVICE_HOST:localhost}
  port: ${BANK_APP_BANK_CHART_SERVICE_PORT:8085}
server:
  port: 8001

keycloak:
  realm: bank
  auth-server-url: http://my-minikube:30598/auth
  resource: product-app
  public-client: true
  enabled: true
  security-constraints[0].authRoles[0]: bank-role
  security-constraints[0].securityCollections[0].patterns[0]: /deposit

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${BANK_APP_RABBITMQ_SERVICE_HOST:localhost}
    username: user
    port: ${BANK_APP_RABBITMQ_PORT_5672_TCP_PORT:5672}
    password: XAZvBI2Mfb
    #FIXME
  cloud:
    stream:
      bindings:
        atmToBank:
          destination: atmToBank
          group: queue
        bankToAtm:
          destination: bankToAtm
          group: queue
        bankToAtmError:
          destination: bankToAtmError
          group: queue