api:
  host: ${BANK_APP_BANK_CHART_SERVICE_HOST:localhost}
  port: 8085
  user: asd
  password: basd
server:
  port: 8001

keycloak:
  realm: bank
  auth-server-url: http://${BANK_APP_KEYCLOAK_HTTP_SERVICE_HOST}:${BANK_APP_KEYCLOAK_HTTP_SERVICE_PORT_HTTP}/auth
  resource: product-app
  public-client: true
  enabled: true
  security-constraints[0].authRoles[0]: bank-role
  security-constraints[0].securityCollections[0].patterns[0]: /deposit

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${BANK_APP_RABBITMQ_SERVICE_HOST}
    username: user
    port: ${BANK_APP_RABBITMQ_PORT_5672_TCP_PORT:5672}
    password: XAZvBI2Mfb
    #FIXME

rabbitmq:
  host: ${BANK_APP_RABBITMQ_SERVICE_HOST}
  port: ${BANK_APP_RABBITMQ_PORT_5672_TCP_PORT:5672}
  user: user
  password: XAZvBI2Mfb
  #FIXME